JETPTMIN=15
JETPTMAX=1000000
JETYMIN=-5.0
JETYMAX=+5.0
DZEROPTMIN=5.0
DZEROPTMAX=100000
DZEROYMIN=-2.0
DZEROYMAX=2.0
TRIGGER=0 # no trigger selection
ISGAMMAN=0
ISDATA=0
SCALEFACTOR=1.0
INPUT=/data/HFJetUPCanalysis/MCSkims23/20250307_ForestHFJetMC23_D0Tagged_v7_pthat5_BeamAandBCombined.root
OUTPUTANALYSIS=output_MC_v10_pthat5_BeamAandBcombined.root


./ExecuteHFJetUPC --Input $INPUT --MinDzeroPT $DZEROPTMIN --MaxDzeroPT $DZEROPTMAX --MinDzeroY $DZEROYMIN --MaxDzeroY $DZEROYMAX --MinJetPT $JETPTMIN --MaxJetPT $JETPTMAX --MinJetY $JETYMIN --MaxJetY $JETYMAX --IsGammaN $ISGAMMAN --TriggerChoice $TRIGGER --IsData $ISDATA --Output $OUTPUTANALYSIS --scaleFactor $SCALEFACTOR
wait
