JETPTMIN=0
JETPTMAX=100000
JETYMIN=-2.4
JETYMAX=+2.4
DZEROPTMIN=2.0
DZEROPTMAX=100000
DZEROYMIN=-2.4
DZEROYMAX=2.4
TRIGGER=2 # no trigger selection
ISGAMMAN=0
ISDATA=1
SCALEFACTOR=1.0
INPUT=/data/HFJetUPCanalysis/DataSkims23/20250113_ForestHFJetData23Skim_2023UPCJanRereco_v4.root
OUTPUTANALYSIS=output_JetPT_ALL.root

./ExecuteHFJetUPC --Input $INPUT --MinDzeroPT $DZEROPTMIN --MaxDzeroPT $DZEROPTMAX --MinDzeroY $DZEROYMIN --MaxDzeroY $DZEROYMAX --MinJetPT $JETPTMIN --MaxJetPT $JETPTMAX --MinJetY $JETYMIN --MaxJetY $JETYMAX --IsGammaN $ISGAMMAN --TriggerChoice $TRIGGER --IsData $ISDATA --Output $OUTPUTANALYSIS --scaleFactor $SCALEFACTOR
wait
